backend:
  name: git-gateway
  branch: main

media_folder: 'public/uploads'
public_folder: '/uploads'

collections:
  - name: 'packages'
    label: 'Packages'
    folder: 'content/packages'
    create: true
    fields:
      - { label: 'Package Name', name: 'name', widget: 'string' }
      - { label: 'Package Description', name: 'description', widget: 'string' }
      - { label: 'Secondary Title', name: 'secondary', widget: 'string' }
      - { label: 'Starting Price', name: 'startingPrice', widget: 'string' }
      - { label: 'Package Features List', name: 'features', widget: 'list' }
